name: "Sphinx: Render docs"

on: 
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Write Google Drive API key to file
      run: |
        echo '${{ secrets.JSON_SECRET }}' > token.json
    - name: Collect survey data
      run: |
        python3 ./scripts/collect_survey.py --SPREADSHEET_ID ${{ secrets.SPREADSHEET_ID }}
    - name: Collect links data
      run: |
        python3 ./scripts/collect_links.py --SPREADSHEET_ID ${{ secrets.SPREADSHEET_ID }}
    - name: Build HTML
      run: |
        make html
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/html